language: perl6
perl6:
  - latest
install:
  - rakudobrew build-zef
  - zef install . --deps-only
script:
  - PERL6_TEST_META=1 PERL6LIB=$PWD/lib zef test .
  - zef install .
  - type 6pm
sudo: false
